# Generated by Django 3.2.4 on 2021-07-06 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_notes_api', '0002_auto_20210706_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='extracted_dates',
            new_name='dates',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='extracted_times',
            new_name='times',
        ),
    ]
